apiVersion: apps/v1
kind: Deployment
metadata:
  name: myindiaproj
  labels:
    app: myindiaproj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myindiaproj
  template:
    metadata:
      labels:
        app: myindiaproj
    spec:
      containers:
      - name: myindiaproj
        image: aravind1721/indiaproj:1.0
        ports:
        - containerPort: 8080
